
spring:
  data:
    cassandra:
      keyspace-name: main
      username: PdyXyrPhPPUPLfyTDkHGShfK
      password: vtlEQ7nucWrUhCPMoaqjU-WZZdg9gi,oG-R5FtmH3Tv7z4sQFDJO+R0phUjLeOgPDYjtKRmdPAMz+4rOYZcUo1Y-a2iT-DRytcj33+_pTyWeYBAo9HyT_W5Iz_9Fx,_I
      schema-action: recreate-drop-unused
      request:
        timeout: 50s
      connection:
        connect-timeout: 50s
        init-query-timeout: 50s
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.50af57be952ad197
            client-secret: ea16cef40c62d4a1e7223463030900b10cad4c13

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: 8a36430f-236f-4573-8eee-18d3ce0036d4-1
    region: asia-south1
    keyspace: main
    application:
      token: AstraCS:PdyXyrPhPPUPLfyTDkHGShfK:8fb6bb648100b95d597dcb13a671de90f2ac214d7a42bd1d798342e5ef0a3e1e